config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # landing page
  root 'users#login'


  devise_for :admins, skip: [:registrations]
  devise_for :instructors, skip: [:registrations]
  devise_for :students, skip: [:registrations]
  devise_for :instructor_applicants
  devise_for :student_applicants




  # resources
  resources :courses
  resources :cohorts
  resources :applications

  # user resources
  resources :admins
  resources :instructors
  resources :students
  resources :instructor_applicants
  resources :student_applicants

  # dashboard
  namespace :dashboard do
    root to: "dashboard#index"
  end

end

app/models/instructor.rb
class Instructor < User
    has_many :cohorts
end

app/controllers/instructors/confirmations_controller.rb
# frozen_string_literal: true

class Instructors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/instructors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Instructors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/instructors/passwords_controller.rb
# frozen_string_literal: true

class Instructors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/instructors/sessions_controller.rb
# frozen_string_literal: true

class Instructors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/instructors/unlocks_controller.rb
# frozen_string_literal: true

class Instructors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  def dashboard
  end

  def index
    @instructors = Instructor.all
    @i = 1
  end

  def show
    @instructor = Instructor.find(params[:id])
    @instructor_admin = Admin.find(@instructor.admin_id)
  end

  def new
    @instructor = Instructor.new
  end
  
  def create
    @instructor = Instructor.create(user_params)
    redirect_to "/instructors/#{@instructor.id}/"
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    @instructor.update(user_params)
    redirect_to "/instructors/#{params[:id]}"
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    redirect_to "/instructors"
  end




  private

  def user_params
    params.require(:instructor).permit(:img_url, :first_name, :last_name, :DOB, :edu_level, :expertise, :position, :hire_date, :salary, :email, :password, :admin_id)
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/create.html.erb
<h1>Instructors#create</h1>
<p>Find me in app/views/instructors/create.html.erb</p>

app/views/instructors/destroy.html.erb
<h1>Instructors#destroy</h1>
<p>Find me in app/views/instructors/destroy.html.erb</p>

app/views/instructors/edit.html.erb
<h1>edit info for your instructor <span class="instructor_name"><%= @instructor.first_name + " " + @instructor.last_name %></span> </h1>

<%= bootstrap_form_for(@instructor) do |f| %>
    <%= f.text_field :img_url, label: "profile img url" %>
    <%= f.text_field :first_name, label: "first name" %>
    <%= f.text_field :last_name, label: "last name" %>
    <%= f.date_field :DOB, label: "date of birth" %>
    <%= f.text_field :edu_level, label: "education level" %>
    <%= f.text_field :expertise, label: "expertise" %>
    <%= f.text_field :position, label: "position" %>
    <%= f.date_field :hire_date, label: "hire date" %>
    <%= f.number_field :salary, label: "salary" %>

    <%= f.email_field :email %>
    <%# f.password_field :password %>

    <%# this will be hidden and automatically set to the session[:id] (the id of the current Admin user) %>
    <%= f.number_field :admin_id, label: "admin id" %>

    <%= f.submit "update instructor info", class: "btn create_btn"%>
	</br>
    </br>

    <a href="/instructors/new"><button class="btn btn-primary add_ppl_btn">create new instructor</button></a>

    </br>
    </br>
<% end %>


<div class="delete_ppl">
<%= form_tag("/students/#{params[:id]}", method: "delete") do %>
<%= submit_tag("delete this instructor", class: "btn btn-danger delete_ppl_btn") %>
<% end %>
</div>



<%#  link_to 'Delete', instructor_path(@instructor), method: :delete, confirm: "Are You Sure You Want To Delete #{@instructor.first_name}?"  %>

app/views/instructors/index.html.erb
<h1>Trampoline Instructors</h1>

</br>
</br>
</br>




<table class="table instructors_table">
  <thead>
    <tr class="table_head">
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Expertise</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <%  @instructors.each do |instructor|  %>
        <tr class="student">
            <th scope="row"><%= @i %></th>
            <td><%= instructor.first_name %></td>
            <td><%= instructor.last_name %></td>
            <td><%= instructor.expertise %></td>
            <td><a href="mailto: <%= instructor.email %>"><%= instructor.email %></a></td>
            <% if admin_signed_in? %>
                <td>
                    <a href="/instructors/<%= instructor.id %>/edit">
                        <button class="btn btn-sm btn-outline-primary">
                            edit
                        </button>
                    </a>
                </td>
                <td>
                

                    <%= form_tag("/instructors/#{instructor.id}", method: "delete", remote: true, confirm: "are you sure") do %>
                        <%= submit_tag("delete", class: "btn btn-sm btn-outline-danger") %>
                    <% end %>
                </td>
            <% end %>
        </tr>
        <% @i += 1 %>
    <% end %>
  </tbody>
</table>

app/views/instructors/new.html.erb
<h1>create a new Instructor</h1>

<%= bootstrap_form_for(@instructor) do |f| %>
    <%= f.text_field :img_url, label: "profile img url" %>
    <%= f.text_field :first_name, label: "first name" %>
    <%= f.text_field :last_name, label: "last name" %>
    <%= f.date_field :DOB, selected: Date.today, min: 150.years.ago, label: "date of birth" %>
    <%= f.text_field :edu_level, label: "education level" %>
    <%= f.text_field :expertise, label: "expertise" %>
    <%= f.text_field :position, label: "position" %>
    <%= f.date_field :hire_date, label: "hire date" %>
    <%= f.number_field :salary, min: 0, label: "salary" %>

    <%= f.email_field :email %>
    <%= f.password_field :password %>

    <%# this will be hidden and automatically set to the session[:id] (the id of the current Admin user) %>
    <%= f.number_field :admin_id, label: "admin id" %>

    <%= f.submit "create instructor", class: "btn create_btn"%>
<% end %>

app/views/instructors/show.html.erb
<h1>Instructors#show</h1>
<p>Find me in app/views/instructors/show.html.erb</p>

</br>
</br>
</br>

<ul class="single_student">
    <li> <%=  @instructor.first_name + " " + @instructor.last_name  %> </li>
    <li> <%=  @instructor.DOB %> </li>
    <li> <%=  @instructor.edu_level %> </li>
    <li> <%=  @instructor.expertise %> </li>
    <li> <%=  @instructor.position %> </li>
    <li> <%=  @instructor.hire_date %> </li>
    <li> <%=  @instructor.salary %> </li>
    <li> <%=    %> </li>
    <li> <%=  @instructor.email %> </li>
    <li> success coach: <%=  @instructor_admin.first_name + " " + @instructor_admin.last_name  %> </li>
</ul>