config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # landing page
  root 'users#login'


  devise_for :admins, skip: [:registrations]
  devise_for :instructors, skip: [:registrations]
  devise_for :students, skip: [:registrations]
  devise_for :instructor_applicants
  devise_for :student_applicants




  # resources
  resources :courses
  resources :cohorts
  resources :applications

  # user resources
  resources :admins
  resources :instructors
  resources :students
  resources :instructor_applicants
  resources :student_applicants

  # dashboard
  namespace :dashboard do
    root to: "dashboard#index"
  end

end

app/models/admin.rb
class Admin < User
    has_many :courses
    has_many :cohorts
    has_many :instructors
    has_many :students

    # def set_type
    #     self.type = 'Admin'
    # end
end

app/models/application.rb
class Application < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
    belongs_to :admin
    belongs_to :instructor

    has_many :cohort_students, :as => :cohort
    has_many :students, :through => :cohort_students , :source => :student
end

app/models/cohort_student.rb
class CohortStudent < ApplicationRecord
    belongs_to :cohort
    belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :cohorts
    belongs_to :admin
end

app/models/instructor.rb
class Instructor < User
    has_many :cohorts
end

app/models/instructor_applicant.rb
class InstructorApplicant < User
    has_one :application
end

app/models/student.rb
class Student < User
    has_many :cohort_students, :as => :student
    has_many :cohorts, :through => :cohort_students , :source => :cohort 

    # def set_type
    #     self.type = 'Student'
    # end
end

app/models/student_applicant.rb
class StudentApplicant < User
    has_one :application
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable, :omniauthable, and :confirmable, 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable

  TYPES = %w( Admin Instructor Student InstructorApplicant StudentApplicant )


  # before_save :set_type
  # validates :type, presence: true, :inclusion => { :in => TYPES }

  # def set_type
  #   # raiser "You must override this method in each model inheriting from Product!"
  # end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate_user!, :only => [:login]
    
    def login 
        puts "I just hit the landing/login page"
    end



    private

    def user_params
      params.require(:user).permit(:type, :img_url, :first_name, :last_name, :DOB, :edu_level, :position, :hire_date, :salary, :email, :password)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def header(text)
        content_for(:header) { text.to_s }
    end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/dashboard/index.html.erb
<%# <h6> dashboard </h6> %>

<% if admin_signed_in? %>
    <div class="dashboard">
        <div class="dashboard_box applications_box">
            <a class="dashboard_resource" href="/applications"><div>Applications</div></a>
        </div>
        <div class="dashboard_box courses_box">
            <a class="dashboard_resource" href="/courses"><div>Courses</div></a>
            <a class="create_new" href="/courses/new"><div>+</div></a>
            <%# link_to '+', new_course_path, class: 'create_new' %>
        </div>
        <div class="dashboard_box cohorts_box">
            <a class="dashboard_resource" href="/cohorts"><div>Cohorts</div></a>
            <a class="create_new" href="/cohorts/new"><div>+</div></a>
        </div>
        <div class="dashboard_box admins_box">
            <a class="dashboard_resource" href="/admins"><div>Trampoline Staff</div></a>
            <a class="create_new" href="/admins/new"><div>+</div></a>
        </div>
        <div class="dashboard_box instructors_box">
            <a class="dashboard_resource" href="/instructors"><div>Instructors</div></a>
            <a class="create_new" href="instructors/new"><div>+</div></a>
        </div>
        <div class="dashboard_box students_box">
            <a class="dashboard_resource" href="/students"><div>Students</div></a>
            <a class="create_new" href="/students/new"><div>+</div></a>
        </div>
        <%# <div class="dashboard_box student_applicants_box">
            <a class="dashboard_resource" href="/student_applicants"><div>Student Applicants</div></a>
        </div>
        <div class="dashboard_box instructor_applicants_box">
            <a class="dashboard_resource" href="/instructor_applicants"><div>Instructor Applicants</div></a>
        </div> %>
    </div>
<% end %>

<% if instructor_signed_in? %>
    <div class="dashboard">
        <div class="dashboard_box courses_box">
            <a class="dashboard_resource" href="/courses"><div>Courses</div></a>
        </div>
        <div class="dashboard_box cohorts_box">
            <a class="dashboard_resource" href="/cohorts"><div>Cohorts</div></a>
        </div>
        <div class="dashboard_box admins_box">
            <a class="dashboard_resource" href="/admins"><div>Trampoline Staff</div></a>
        </div>
        <div class="dashboard_box students_box">
            <a class="dashboard_resource" href="/students"><div>Your Students</div></a>
        </div>
        <div class="dashboard_box instructors_box">
            <a class="dashboard_resource" href="/instructors"><div>Instructors</div></a>
        </div>
    </div>
<% end %>

<% if student_signed_in? %>
    <div class="dashboard">
        <div class="dashboard_box courses_box">
            <a class="dashboard_resource" href="/courses"><div>Courses</div></a>
        </div>
        <div class="dashboard_box cohorts_box">
            <a class="dashboard_resource" href="/cohorts"><div>Your Cohorts</div></a>
        </div>
        <div class="dashboard_box admins_box">
            <a class="dashboard_resource" href="/admins"><div>Trampoline Staff</div></a>
        </div>
        <div class="dashboard_box instructors_box">
            <a class="dashboard_resource" href="/instructors"><div>Instructors</div></a>
        </div>
    </div>
<% end %>

<% if instructor_applicant_signed_in? %>
    <div class="dashboard_box applications_box">
        <a class="dashboard_resource" href="#"><div>Your Application</div></a>
    </div>
<% end %>

<% if student_applicant_signed_in? %>
    <div class="dashboard_box applications_box">
        <a class="dashboard_resource" href="#"><div>Your Application</div></a>
    </div>
<% end %>